set(CTEST_CUSTOM_TESTS_IGNORE
      demangle
      logging
      signalhandler
      stacktrace
      stl_logging
      symbolize
      cmake_package_config_init
      cmake_package_config_generate
      cleanup_immediately
      cleanup_with_absolute_prefix
      cleanup_with_relative_prefix
      cmake_package_config_build
      logging_custom_prefix
      cmake_package_config_cleanup
      cleanup_init
      cleanup_logdir
      )
